name: build

on: [push, pull_request]

jobs:
  build-and-tests:
    name: "build-and-tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build and test
        run: dotnet test
